### ISSUE TITLE
拖动出新view的效果

### ISSUE THREAD

**Issue by Mil0R** [chenqihui/NewsFourApp#1]
有一个效果，试了很多方法都不理想。新闻详情页面，向左拖动可以把评论页拉出来，效果跟拖动返回一样。

**Comment by chenqihui** [comment]
你的思路是咋样的呢？？
第一反应，或许可以参考我在首页拖出右边菜单页面的方式来实现。呵呵～～

**Comment by Mil0R** [comment]
@chenqihui 应该不是scroll，是navigation。

**Comment by chenqihui** [comment]
……呵呵，拖出右边菜单跟scroll没有联系的。你可以去掉首页的所有东西，只留下一个空白的view，应该就明白我的意思了

**Comment by Mil0R** [comment]
看到了，大约知道了你的意思，回头试下，谢谢。
