### ISSUE TITLE
怎么像网易客户端那样，点击左侧菜单时，改变MainVC？

### ISSUE THREAD

**Issue by Alsen007** [chenqihui/NewsFourApp#2]
怎么改变MainVC主视图控制器

**Comment by chenqihui** [comment]
你可以使用通知，也可以直接在点击左菜单，之后就是改变MainVC里面用于展示的view，MainVC可以通过QHSliderViewController获取，你也可以写在你觉得方便的地方，便于管理。

**Comment by Alsen007** [comment]
可以直接改变MainVC的viewcontroller吗？改变后又该如何显示新的mainVC，可以给个代码示例吗？

**Comment by chenqihui** [comment]
你的viewcontroller或者view，直接[MainVC.view addSubView:viewcontroller.view或者view], 同步执行下closeSideBar~~

你也可以直接使用
- (void)closeSideBarWithAnimate:(BOOL)bAnimate complete:(void(^)(BOOL finished))complete;
  在block里面操作addsubview

**Comment by Alsen007** [comment]
我试了下，程序会崩掉。我在你的NewsFourApp中，LeftViewController->toNewViewbtn方法：改成
[[QHSliderViewController sharedSliderController] closeSideBarWithAnimate:YES complete:^(BOOL finished)
    {
        SubViewController *subViewController = [[SubViewController alloc] initWithFrame:[UIScreen mainScreen].bounds andSignal:@"new view"];
        [[QHSliderViewController sharedSliderController].MainVC.view addSubview:subViewController.view];
    }];
成功跳转后，点击subview程序就崩掉了。帮忙看下问题怎么解决？

**Comment by Alsen007** [comment]
好像可以了，我再试试，谢谢

**Comment by Alsen007** [comment]
不行的，MainVC.view addSubview:subViewController.view 后，在subViewController.view上的任何操作点击、返回、push新的viewcontroller都会崩溃。

**Comment by chenqihui** [comment]
你把跳转的函数写在MainVC里面，在subViewController.view点击触发的事件时调用[MainVC push];

你最好也看清楚你的奔溃信息
